// Smart Global ERP — Module registry (all 50 modules)
// Each module belongs to a category and exposes a feature list.

export type ModuleCategory =
  | "Executive"
  | "Sales & CRM"
  | "Purchase & Inventory"
  | "HR & Finance"
  | "Operations"
  | "System"
  | "Advanced";

export interface ModuleDef {
  id: string;            // kebab-case id used as URL-less route key
  number: number;        // 1..50
  name: string;          // Display name
  shortName?: string;    // Compact sidebar label
  category: ModuleCategory;
  icon: string;          // lucide-react icon name (we map to component in Sidebar)
  description: string;
  features: string[];
  /** Render variant for the module content area. */
  variant:
    | "executive-dashboard"
    | "vendors-dashboard"
    | "crm"
    | "sales"
    | "purchase"
    | "inventory"
    | "pos"
    | "product"
    | "hr"
    | "finance"
    | "reports"
    | "manufacturing"
    | "generic";
}

export const MODULE_CATEGORIES: ModuleCategory[] = [
  "Executive",
  "Sales & CRM",
  "Purchase & Inventory",
  "HR & Finance",
  "Operations",
  "System",
  "Advanced",
];

export const MODULES: ModuleDef[] = [
  {
    id: "executive-dashboard",
    number: 1,
    name: "Executive Dashboard",
    shortName: "Dashboard",
    category: "Executive",
    icon: "LayoutDashboard",
    description: "CEO Command Center — Real-time overview of your entire business",
    variant: "executive-dashboard",
    features: [
      "CEO Dashboard", "Executive Dashboard", "Business Overview", "Real-Time Analytics",
      "KPI Dashboard", "Revenue Dashboard", "Profit & Loss Overview", "Sales Analytics",
      "Purchase Analytics", "Production Analytics", "Inventory Analytics", "Financial Dashboard",
      "AI Business Insights", "Performance Reports", "Live Charts & Graphs", "Custom Widgets",
      "Department Overview", "Company Performance", "User Activity", "Export Dashboard Reports",
    ],
  },
  {
    id: "crm",
    number: 2,
    name: "CRM",
    shortName: "CRM",
    category: "Sales & CRM",
    icon: "Users",
    description: "Customer Relationship Management — Leads, opportunities, pipeline",
    variant: "crm",
    features: [
      "Customer Database", "Customer Profile", "Customer Segmentation", "Lead Management",
      "Opportunity Management", "Sales Pipeline", "Customer Follow-up", "Meeting Scheduler",
      "Call Logs", "Email Tracking", "WhatsApp Integration", "Customer Notes",
      "Customer Documents", "Customer Timeline", "Customer Feedback", "Customer Loyalty",
      "Customer Wallet", "Customer Support", "Customer Reports", "CRM Analytics",
    ],
  },
  {
    id: "buyers-suppliers",
    number: 3,
    name: "Buyer & Supplier Management",
    shortName: "Vendors",
    category: "Purchase & Inventory",
    icon: "Handshake",
    description: "Manage & monitor all buyers, suppliers and vendors in one place",
    variant: "vendors-dashboard",
    features: [
      "Buyer Management", "Supplier Management", "Buyer Profile", "Supplier Profile",
      "Buyer Contracts", "Supplier Contracts", "Purchase History", "Sales History",
      "Vendor Rating", "Credit Limit", "Due Management", "Payment History",
      "Contact Directory", "Document Storage", "Country Management", "Communication History",
      "Buyer Performance", "Supplier Performance", "Reports", "Analytics",
    ],
  },
  {
    id: "marketplace",
    number: 4,
    name: "Multi-Vendor Marketplace",
    shortName: "Marketplace",
    category: "Sales & CRM",
    icon: "Store",
    description: "Vendor onboarding, store management, commissions and payouts",
    variant: "generic",
    features: [
      "Vendor Registration", "Vendor Approval", "Vendor Dashboard", "Vendor Store Management",
      "Product Approval", "Commission Management", "Vendor Wallet", "Vendor Payout",
      "Withdrawal Request", "Sales Report", "Product Report", "Vendor Analytics",
      "Store Verification", "Vendor Subscription", "Vendor Chat", "Vendor Notification",
      "Return Management", "Refund Management", "Vendor Performance", "Marketplace Reports",
    ],
  },
  {
    id: "products",
    number: 5,
    name: "Product Management",
    shortName: "Products",
    category: "Purchase & Inventory",
    icon: "Package",
    description: "Catalog, categories, variants, SKUs, barcodes & pricing",
    variant: "product",
    features: [
      "Product Management", "Product Categories", "Brand Management", "Product Variants",
      "SKU Management", "Barcode Generation", "QR Code Support", "Product Images",
      "Product Videos", "Product Tags", "Product Attributes", "Product Pricing",
      "Product Discounts", "Bulk Import", "Bulk Export", "Product Reviews",
      "Product Approval", "Product SEO", "Product History", "Product Reports",
    ],
  },
  {
    id: "sales",
    number: 6,
    name: "Sales Management",
    shortName: "Sales",
    category: "Sales & CRM",
    icon: "ShoppingCart",
    description: "Sales orders, quotations, invoices, returns & due collection",
    variant: "sales",
    features: [
      "Sales Orders", "Quotations", "Invoice Management", "Sales Return",
      "Credit Sales", "Cash Sales", "Online Sales", "Offline Sales",
      "Discount Management", "Sales Commission", "Customer Payments", "Due Collection",
      "Sales Reports", "Sales Analytics", "Tax Calculation", "Delivery Notes",
      "Proforma Invoice", "Payment Tracking", "Order Status", "Sales Dashboard",
    ],
  },
  {
    id: "purchase",
    number: 7,
    name: "Purchase Management",
    shortName: "Purchase",
    category: "Purchase & Inventory",
    icon: "Truck",
    description: "Purchase orders, GRN, approvals, supplier payments",
    variant: "purchase",
    features: [
      "Purchase Orders", "Supplier Quotations", "Goods Receive Note (GRN)", "Purchase Return",
      "Purchase Approval", "Supplier Payment", "Purchase History", "Purchase Analytics",
      "Purchase Reports", "Tax Management", "Cost Analysis", "Order Tracking",
      "Due Management", "Expense Allocation", "Procurement Workflow", "Multi Supplier Support",
      "Purchase Dashboard", "Bulk Purchase", "Auto Reorder", "Purchase Notifications",
    ],
  },
  {
    id: "inventory",
    number: 8,
    name: "Inventory & Warehouse",
    shortName: "Inventory",
    category: "Purchase & Inventory",
    icon: "Warehouse",
    description: "Multi-warehouse stock, transfers, adjustments, batch & serial tracking",
    variant: "inventory",
    features: [
      "Stock Management", "Warehouse Management", "Multi Warehouse", "Stock Transfer",
      "Stock Adjustment", "Stock Count", "Barcode Scanning", "QR Code Inventory",
      "Batch Tracking", "Serial Number Tracking", "Expiry Tracking", "Low Stock Alerts",
      "Warehouse Reports", "Stock Valuation", "Inventory Forecast", "Goods Movement",
      "Bin Location", "Inventory Audit", "Inventory Dashboard", "Inventory Analytics",
    ],
  },
  {
    id: "pos",
    number: 9,
    name: "POS (Point of Sale)",
    shortName: "POS",
    category: "Sales & CRM",
    icon: "CreditCard",
    description: "Touch POS for retail, restaurant, pharmacy, garments & multi-counter",
    variant: "pos",
    features: [
      "Touch POS", "Barcode POS", "Restaurant POS", "Retail POS",
      "Pharmacy POS", "Garments POS", "Multi Counter POS", "Multi Branch POS",
      "Offline POS", "Online POS", "Customer Display", "Thermal Printing",
      "Cash Drawer Support", "Loyalty Program", "Gift Card", "Discount System",
      "Coupon Support", "Split Payment", "Returns & Exchange", "POS Reports",
    ],
  },
  {
    id: "ecommerce",
    number: 10,
    name: "E-Commerce Management",
    shortName: "E-Commerce",
    category: "Sales & CRM",
    icon: "Globe",
    description: "Online store, website builder, themes, banners, SEO, coupons, courier",
    variant: "generic",
    features: [
      "Online Store", "Website Builder", "Theme Management", "Banner Management",
      "Slider Management", "Product SEO", "Blog Management", "Coupon System",
      "Flash Sale", "Wishlist", "Compare Products", "Product Reviews",
      "Order Tracking", "Live Chat", "Payment Gateway", "Courier Integration",
      "Multi Currency", "Multi Language", "Mobile Responsive", "E-Commerce Analytics",
    ],
  },
  {
    id: "manufacturing",
    number: 11,
    name: "Manufacturing Management",
    shortName: "Manufacturing",
    category: "Operations",
    icon: "Factory",
    description: "Production planning, BOM, work orders, machine & labour allocation",
    variant: "manufacturing",
    features: [
      "Production Planning", "Bill of Materials (BOM)", "Work Orders", "Production Schedule",
      "Machine Allocation", "Labour Allocation", "Material Requirement Planning", "Production Costing",
      "Quality Check", "Production Reports", "Work Center", "Routing Management",
      "Production Tracking", "Scrap Management", "Subcontracting", "Production Forecasting",
      "Capacity Planning", "Production Analytics", "Manufacturing Dashboard", "Auto Scheduling",
    ],
  },
  {
    id: "garments-merchandising",
    number: 12,
    name: "Garments Merchandising",
    shortName: "Merchandising",
    category: "Operations",
    icon: "Shirt",
    description: "Garments-specific merchandising — orders, styles, BOM, costing",
    variant: "generic",
    features: [
      "Order Management", "Style Management", "Sample Development", "Costing Sheet",
      "BOM for Garments", "Fabric Booking", "Trims Management", "Wash Care Label",
      "Size & Color Matrix", "Production Follow-up", "Shipment Tracking", "Buyer Compliance",
      "Tech Pack Management", "Bulk Order", "Sample Approval", "Production Approval",
      "Quality Standard", "Inspection Report", "Buyer Communication", "Merchandising Reports",
    ],
  },
  {
    id: "sample-development",
    number: 13,
    name: "Sample Development",
    shortName: "Sample Dev",
    category: "Operations",
    icon: "FlaskConical",
    description: "Sample request, prototype tracking, approval workflow",
    variant: "generic",
    features: [
      "Sample Request", "Prototype Tracking", "Sample Approval", "Sample Costing",
      "Sample Inventory", "Buyer Sample", "Sample Workflow", "Sample Status",
      "Sample History", "Sample Reports", "Design File Upload", "Tech Pack Upload",
      "Sample Calendar", "Sample Feedback", "Sample Revision", "Bulk Conversion",
      "Sample Pricing", "Sample Logistics", "Sample Dashboard", "Sample Analytics",
    ],
  },
  {
    id: "quality-control",
    number: 14,
    name: "Quality Control (QC)",
    shortName: "QC",
    category: "Operations",
    icon: "ShieldCheck",
    description: "Inspection plans, defect tracking, QC reports & compliance",
    variant: "generic",
    features: [
      "Inspection Plan", "QC Checkpoints", "Defect Tracking", "Inspection Report",
      "AQL Sampling", "QC Approval", "QC Rejection", "Rework Order",
      "Quality Standard", "Compliance Report", "Defect Analysis", "QC Dashboard",
      "Inspector Management", "QC Workflow", "QC Analytics", "Audit Report",
      "Final Inspection", "In-line Inspection", "Pre-shipment Inspection", "QC Reports",
    ],
  },
  {
    id: "hr",
    number: 15,
    name: "HR Management",
    shortName: "HR",
    category: "HR & Finance",
    icon: "UserCog",
    description: "Employee lifecycle, departments, designations, recruitment & onboarding",
    variant: "hr",
    features: [
      "Employee Database", "Department Management", "Designation Management", "Recruitment",
      "Onboarding", "Offboarding", "Employee Transfer", "Promotion Management",
      "Performance Review", "Leave Management", "Employee Documents", "Employee Timeline",
      "Training Management", "Employee Self Service", "HR Reports", "HR Analytics",
      "Employee Directory", "Org Chart", "Employee Engagement", "HR Dashboard",
    ],
  },
  {
    id: "attendance",
    number: 16,
    name: "Attendance Management",
    shortName: "Attendance",
    category: "HR & Finance",
    icon: "CalendarCheck",
    description: "Biometric & manual attendance, shift, overtime, leave ledger",
    variant: "generic",
    features: [
      "Daily Attendance", "Biometric Integration", "Manual Attendance", "Shift Management",
      "Overtime Tracking", "Leave Ledger", "Attendance Regularization", "Late & Early Tracking",
      "Holiday Management", "Weekend Policy", "Attendance Reports", "Attendance Analytics",
      "Punch In/Out", "Face Recognition", "GPS Attendance", "Mobile Attendance",
      "Shift Roaster", "Attendance Approval", "Attendance Dashboard", "Export Reports",
    ],
  },
  {
    id: "payroll",
    number: 17,
    name: "Payroll Management",
    shortName: "Payroll",
    category: "HR & Finance",
    icon: "Banknote",
    description: "Salary structure, payslip, bonus, deductions & payroll processing",
    variant: "generic",
    features: [
      "Salary Structure", "Payroll Processing", "Payslip Generation", "Bonus Management",
      "Deduction Management", "Tax Calculation", "Overtime Pay", "Allowance Management",
      "Loan Management", "Salary Advance", "Payroll Approval", "Bank Transfer File",
      "Payroll Reports", "Payroll Analytics", "Payroll History", "Employee Payroll",
      "Statutory Compliance", "Year-end Report", "Payroll Dashboard", "Bulk Payslip",
    ],
  },
  {
    id: "finance",
    number: 18,
    name: "Finance & Accounting",
    shortName: "Finance",
    category: "HR & Finance",
    icon: "Landmark",
    description: "Chart of accounts, journal, ledger, P&L, balance sheet, trial balance",
    variant: "finance",
    features: [
      "Chart of Accounts", "Journal Entry", "General Ledger", "Trial Balance",
      "Profit & Loss Statement", "Balance Sheet", "Cash Flow Statement", "Bank Reconciliation",
      "Accounts Receivable", "Accounts Payable", "Tax Management", "VAT Management",
      "Cost Center", "Budgeting", "Financial Reports", "Financial Dashboard",
      "Multi Currency", "Fiscal Year", "Auto Posting", "Financial Analytics",
    ],
  },
  {
    id: "banking",
    number: 19,
    name: "Banking & Payment Management",
    shortName: "Banking",
    category: "HR & Finance",
    icon: "CreditCard",
    description: "Bank accounts, transactions, transfers, payment gateways",
    variant: "generic",
    features: [
      "Bank Account Management", "Bank Transaction", "Bank Transfer", "Cheque Management",
      "Payment Gateway", "Online Payment", "Mobile Banking", "Payment Reconciliation",
      "Payment History", "Bank Statement", "Bank Reconciliation", "Payment Approval",
      "Multi Bank Account", "Bank Reports", "Bank Dashboard", "Payment Analytics",
      "Refund Management", "Payment Links", "Banking Analytics", "Banking Notifications",
    ],
  },
  {
    id: "courier-logistics",
    number: 20,
    name: "Courier & Logistics",
    shortName: "Logistics",
    category: "Operations",
    icon: "Truck",
    description: "Shipment booking, tracking, dispatch, delivery & rider management",
    variant: "generic",
    features: [
      "Shipment Booking", "Shipment Tracking", "Dispatch Management", "Delivery Management",
      "Rider Management", "Hub Management", "Route Optimization", "Delivery Proof",
      "COD Management", "Return Management", "Courier Reports", "Courier Analytics",
      "Tracking Number", "Multi Courier", "API Integration", "Courier Dashboard",
      "Delivery Status", "Pickup Management", "Shipment History", "Delivery Reports",
    ],
  },
  {
    id: "dms",
    number: 21,
    name: "Document Management System",
    shortName: "DMS",
    category: "System",
    icon: "FolderArchive",
    description: "Digital file storage, version control, approval workflow, OCR search",
    variant: "generic",
    features: [
      "Document Upload", "Digital File Storage", "Folder Management", "File Version Control",
      "Document Approval Workflow", "Digital Signature", "OCR Document Search", "PDF Preview",
      "Access Permission", "Document Sharing", "File History", "File Recovery",
      "Cloud Storage", "File Encryption", "Audit Trail", "Expiry Reminder",
      "Archive Management", "Download Logs", "Bulk Upload", "Document Reports",
    ],
  },
  {
    id: "fixed-asset",
    number: 22,
    name: "Fixed Asset Management",
    shortName: "Assets",
    category: "HR & Finance",
    icon: "Boxes",
    description: "Asset registration, allocation, depreciation & disposal",
    variant: "generic",
    features: [
      "Asset Registration", "Asset Categories", "Asset Barcode", "Asset QR Code",
      "Asset Allocation", "Asset Transfer", "Asset Maintenance", "Depreciation Calculation",
      "Asset Disposal", "Asset Repair History", "Warranty Tracking", "Asset Insurance",
      "Asset Verification", "Asset Reports", "Asset Dashboard", "Asset Audit",
      "Asset Tracking", "Purchase History", "Vendor Details", "Asset Analytics",
    ],
  },
  {
    id: "helpdesk",
    number: 23,
    name: "Customer Support (Help Desk)",
    shortName: "Help Desk",
    category: "Sales & CRM",
    icon: "Headphones",
    description: "Tickets, live chat, SLA, knowledge base, AI chatbot",
    variant: "generic",
    features: [
      "Support Ticket", "Live Chat", "WhatsApp Support", "Email Support",
      "Knowledge Base", "FAQ Management", "Complaint Management", "Ticket Assignment",
      "Ticket Priority", "SLA Management", "Customer Feedback", "Remote Support",
      "Ticket Status", "Ticket History", "Support Dashboard", "Performance Report",
      "Customer Satisfaction", "AI Chatbot", "Auto Reply", "Help Desk Analytics",
    ],
  },
  {
    id: "project-management",
    number: 24,
    name: "Project Management",
    shortName: "Projects",
    category: "Operations",
    icon: "KanbanSquare",
    description: "Tasks, milestones, Gantt, Kanban, budget, time tracking",
    variant: "generic",
    features: [
      "Project Creation", "Task Management", "Milestone Tracking", "Team Assignment",
      "Time Tracking", "Gantt Chart", "Kanban Board", "Project Budget",
      "Expense Tracking", "File Sharing", "Project Calendar", "Resource Planning",
      "Risk Management", "Issue Tracking", "Project Reports", "Project Dashboard",
      "Team Chat", "Notifications", "Progress Analytics", "Client Portal",
    ],
  },
  {
    id: "multi-company",
    number: 25,
    name: "Multi-Company Management",
    shortName: "Multi-Company",
    category: "System",
    icon: "Building2",
    description: "Unlimited companies with separate DBs, branding, financial reports",
    variant: "generic",
    features: [
      "Unlimited Companies", "Separate Database", "Company Dashboard", "Company Reports",
      "Company Branding", "Company Settings", "Company Tax Rules", "Company Users",
      "Company Roles", "Company Documents", "Company Financial Reports", "Shared Resources",
      "Company Approval", "Company Notifications", "Company Analytics", "Company Backup",
      "Company API", "Company Logs", "Cross Company Reports", "Company Security",
    ],
  },
  {
    id: "multi-branch",
    number: 26,
    name: "Multi-Branch Management",
    shortName: "Branches",
    category: "System",
    icon: "GitBranch",
    description: "Branch-wise inventory, sales, purchase, accounting & reports",
    variant: "generic",
    features: [
      "Branch Setup", "Branch Dashboard", "Branch Inventory", "Branch Sales",
      "Branch Purchase", "Branch Accounting", "Branch Employees", "Branch Attendance",
      "Branch Transfers", "Branch Warehouse", "Branch Reports", "Branch Analytics",
      "Branch Performance", "Branch Notifications", "Branch Permissions", "Branch Settings",
      "Branch Expenses", "Branch Income", "Branch Audit", "Branch Backup",
    ],
  },
  {
    id: "multi-currency",
    number: 27,
    name: "Multi-Currency & Language",
    shortName: "Currency/Lang",
    category: "System",
    icon: "Languages",
    description: "Multi-currency, exchange rates, multi-language, RTL & localization",
    variant: "generic",
    features: [
      "Multi Currency", "Exchange Rate", "Auto Currency Update", "Currency Converter",
      "Multi Language", "RTL Language Support", "Country Settings", "Time Zone",
      "Date Format", "Number Format", "Localization", "Currency Reports",
      "Tax by Country", "Regional Settings", "Language Pack", "Translation Management",
      "Country Analytics", "Country Dashboard", "Global Settings", "International Business Support",
    ],
  },
  {
    id: "subscription",
    number: 28,
    name: "Subscription & Billing",
    shortName: "Subscriptions",
    category: "HR & Finance",
    icon: "Repeat",
    description: "Plans, free trial, recurring billing, invoices & auto-suspension",
    variant: "generic",
    features: [
      "Subscription Plans", "Free Trial", "Monthly Billing", "Yearly Billing",
      "Invoice Generation", "Automatic Renewal", "Recurring Payments", "Usage Tracking",
      "Plan Upgrade", "Plan Downgrade", "Payment Reminder", "Billing Reports",
      "Tax Invoice", "Customer Subscription", "Coupon Support", "Discount Management",
      "Billing Dashboard", "Revenue Analytics", "Subscription History", "Auto Suspension",
    ],
  },
  {
    id: "ai-bi",
    number: 29,
    name: "AI & Business Intelligence",
    shortName: "AI/BI",
    category: "Advanced",
    icon: "Brain",
    description: "Predictive analytics, forecasting, smart reports & AI automation",
    variant: "generic",
    features: [
      "AI Dashboard", "Predictive Analytics", "Business Forecast", "Smart Reports",
      "KPI Analytics", "AI Sales Prediction", "AI Inventory Forecast", "AI Financial Analysis",
      "AI Production Planning", "AI Demand Forecast", "AI Alerts", "Smart Recommendations",
      "Customer Insights", "Heat Map", "Interactive Charts", "Executive Reports",
      "Data Visualization", "Business Intelligence", "AI Automation", "AI Assistant",
    ],
  },
  {
    id: "reports-analytics",
    number: 30,
    name: "Reports & Analytics",
    shortName: "Reports",
    category: "System",
    icon: "BarChart3",
    description: "Sales, purchase, inventory, finance, HR & custom reports",
    variant: "reports",
    features: [
      "Sales Reports", "Purchase Reports", "Inventory Reports", "Production Reports",
      "Financial Reports", "HR Reports", "Payroll Reports", "Attendance Reports",
      "Customer Reports", "Vendor Reports", "Buyer Reports", "Warehouse Reports",
      "Branch Reports", "Company Reports", "Tax Reports", "Profit & Loss Reports",
      "Dashboard Reports", "Excel Export", "PDF Export", "Custom Reports",
    ],
  },
  {
    id: "api-integration",
    number: 31,
    name: "API & Third-Party Integration",
    shortName: "API/Integrations",
    category: "System",
    icon: "Plug",
    description: "REST, GraphQL, webhooks, OAuth, payment/SMS/WhatsApp gateways",
    variant: "generic",
    features: [
      "REST API", "GraphQL API", "Webhook Support", "API Authentication",
      "API Key Management", "OAuth 2.0", "Payment Gateway Integration", "SMS Gateway Integration",
      "Email Service Integration", "WhatsApp API", "Google Maps Integration", "ERP API",
      "Mobile API", "Accounting API", "Shipping API", "Marketplace API",
      "Web Service Integration", "API Documentation", "API Logs", "API Analytics",
    ],
  },
  {
    id: "security-access",
    number: 32,
    name: "Security & Access Control",
    shortName: "Security",
    category: "System",
    icon: "ShieldCheck",
    description: "Roles, permissions, 2FA, SSO, IP whitelist, audit trail",
    variant: "generic",
    features: [
      "Role Management", "Permission Management", "User Access Control", "Two-Factor Authentication (2FA)",
      "Single Sign-On (SSO)", "Password Policy", "Login History", "IP Whitelist",
      "Device Management", "Session Management", "Data Encryption", "SSL Security",
      "Firewall Integration", "User Activity Log", "Security Alerts", "Audit Trail",
      "Account Lock", "Backup Authentication", "Access Reports", "Security Dashboard",
    ],
  },
  {
    id: "workflow",
    number: 33,
    name: "Workflow & Approval",
    shortName: "Workflow",
    category: "System",
    icon: "Workflow",
    description: "Multi-level approvals, escalation rules, custom workflows",
    variant: "generic",
    features: [
      "Workflow Builder", "Multi-Level Approval", "Purchase Approval", "Sales Approval",
      "Expense Approval", "Leave Approval", "Payroll Approval", "Production Approval",
      "Document Approval", "Task Approval", "Auto Workflow", "Approval Notifications",
      "Escalation Rules", "Workflow History", "Approval Dashboard", "Custom Workflow",
      "Department Workflow", "Workflow Reports", "AI Approval Suggestions", "Workflow Analytics",
    ],
  },
  {
    id: "notifications",
    number: 34,
    name: "Notification Center",
    shortName: "Notifications",
    category: "System",
    icon: "Bell",
    description: "Email, SMS, WhatsApp, push, in-app notifications & templates",
    variant: "generic",
    features: [
      "Email Notifications", "SMS Notifications", "WhatsApp Notifications", "Push Notifications",
      "In-App Notifications", "Order Alerts", "Payment Alerts", "Stock Alerts",
      "Attendance Alerts", "Approval Alerts", "System Alerts", "Reminder Notifications",
      "Marketing Notifications", "Broadcast Messages", "Notification Templates", "Notification History",
      "Auto Notifications", "Event Triggers", "Notification Reports", "Notification Dashboard",
    ],
  },
  {
    id: "audit-compliance",
    number: 35,
    name: "Audit & Compliance",
    shortName: "Audit",
    category: "System",
    icon: "ScrollText",
    description: "Audit logs, ISO/GDPR/tax compliance, risk assessment",
    variant: "generic",
    features: [
      "Audit Log", "Activity History", "User Tracking", "Compliance Reports",
      "ISO Compliance", "GDPR Compliance", "Tax Compliance", "Financial Audit",
      "Inventory Audit", "HR Audit", "Security Audit", "Data Retention Policy",
      "Risk Assessment", "Internal Audit", "External Audit", "Compliance Dashboard",
      "Audit Reports", "Audit Notifications", "Audit Analytics", "Digital Audit Trail",
    ],
  },
  {
    id: "backup-recovery",
    number: 36,
    name: "Backup & Disaster Recovery",
    shortName: "Backup",
    category: "System",
    icon: "DatabaseBackup",
    description: "Automatic & manual backup, cloud restore, encryption",
    variant: "generic",
    features: [
      "Automatic Backup", "Manual Backup", "Cloud Backup", "Local Backup",
      "Database Backup", "File Backup", "Backup Scheduling", "One Click Restore",
      "Disaster Recovery", "Backup Encryption", "Version Backup", "Incremental Backup",
      "Backup Verification", "Restore Point", "Multi-Server Backup", "Backup Reports",
      "Recovery Reports", "Backup Notifications", "Backup Dashboard", "Recovery Analytics",
    ],
  },
  {
    id: "mobile-app",
    number: 37,
    name: "Mobile App Management",
    shortName: "Mobile",
    category: "System",
    icon: "Smartphone",
    description: "Android/iOS app for CRM, sales, inventory, attendance & approvals",
    variant: "generic",
    features: [
      "Android App", "iOS App", "Mobile Dashboard", "Mobile CRM",
      "Mobile Sales", "Mobile Purchase", "Mobile Inventory", "Mobile Accounting",
      "Mobile Attendance", "Mobile Payroll", "Mobile Notifications", "Offline Mode",
      "Data Synchronization", "QR Scanner", "Barcode Scanner", "GPS Tracking",
      "Mobile Reports", "Mobile Security", "App Settings", "Mobile Analytics",
    ],
  },
  {
    id: "iot",
    number: 38,
    name: "IoT & Smart Devices",
    shortName: "IoT",
    category: "Advanced",
    icon: "Cpu",
    description: "Biometric, RFID, GPS, smart sensors, machine monitoring",
    variant: "generic",
    features: [
      "Fingerprint Machine Integration", "Face Recognition Integration", "RFID Integration", "Barcode Scanner",
      "QR Scanner", "Biometric Devices", "Smart Sensors", "GPS Device Integration",
      "Machine Monitoring", "Production Machine Integration", "Weight Scale Integration", "Printer Integration",
      "POS Hardware Integration", "CCTV Integration", "Smart Gate Access", "IoT Dashboard",
      "Device Health Monitoring", "Device Alerts", "IoT Reports", "Device Analytics",
    ],
  },
  {
    id: "cloud-server",
    number: 39,
    name: "Cloud & Server Management",
    shortName: "Cloud",
    category: "System",
    icon: "Server",
    description: "Multi-tenant, load balancing, auto-scaling, CDN, monitoring",
    variant: "generic",
    features: [
      "Multi-Tenant Architecture", "Cloud Hosting", "Dedicated Server Support", "Load Balancing",
      "Auto Scaling", "Database Replication", "CDN Integration", "Server Monitoring",
      "Performance Optimization", "Cache Management", "Storage Management", "Server Logs",
      "Resource Monitoring", "Server Backup", "High Availability", "Failover Support",
      "SSL Management", "Domain Management", "Server Analytics", "Cloud Dashboard",
    ],
  },
  {
    id: "system-admin",
    number: 40,
    name: "System Administration",
    shortName: "Admin",
    category: "System",
    icon: "Settings",
    description: "System configuration, theme, dark mode, license & maintenance",
    variant: "generic",
    features: [
      "System Configuration", "Company Settings", "Branch Settings", "User Management",
      "Role Management", "Permission Management", "Language Settings", "Currency Settings",
      "Theme Management", "Dark Mode", "Email Settings", "SMS Settings",
      "Payment Settings", "Tax Settings", "Backup Settings", "System Logs",
      "License Management", "Maintenance Mode", "System Health Monitor", "Admin Dashboard",
    ],
  },
  {
    id: "ai-copilot",
    number: 41,
    name: "AI Copilot & Assistant",
    shortName: "AI Copilot",
    category: "Advanced",
    icon: "Bot",
    description: "AI chat, smart search, voice commands, report generation",
    variant: "generic",
    features: [
      "AI Chat Assistant", "Smart Search", "Voice Commands", "AI Report Generator",
      "AI Data Analysis", "AI Recommendations", "AI Forecasting", "AI Workflow Automation",
      "AI Error Detection", "AI Notifications", "AI Business Insights", "AI Decision Support",
      "AI Sales Prediction", "AI Inventory Prediction", "AI Customer Support", "AI Document Summary",
      "AI Translation", "AI Dashboard", "AI Learning Engine", "AI Performance Analytics",
    ],
  },
  {
    id: "automation",
    number: 42,
    name: "Business Process Automation",
    shortName: "Automation",
    category: "Advanced",
    icon: "Zap",
    description: "Auto invoice, PO, stock, payroll, notifications & scheduled tasks",
    variant: "generic",
    features: [
      "Workflow Automation", "Auto Invoice", "Auto Purchase Order", "Auto Stock Update",
      "Auto Payroll", "Auto Attendance Sync", "Auto Notifications", "Auto Email",
      "Auto SMS", "Auto WhatsApp", "Auto Backup", "Auto Report Generation",
      "Auto Tax Calculation", "Auto Currency Update", "Scheduled Tasks", "Trigger-Based Actions",
      "Rule Engine", "Approval Automation", "Process Monitoring", "Automation Analytics",
    ],
  },
  {
    id: "marketplace-advanced",
    number: 43,
    name: "Marketplace Advanced",
    shortName: "Marketplace Pro",
    category: "Sales & CRM",
    icon: "Store",
    description: "Featured vendors, ratings, promotions, global marketplace",
    variant: "generic",
    features: [
      "Multi-Vendor Marketplace", "Vendor Subscription", "Commission Management", "Vendor Wallet",
      "Vendor Payout", "Store Verification", "Store Rating", "Marketplace Promotions",
      "Featured Vendors", "Featured Products", "Vendor Chat", "Vendor Analytics",
      "Vendor Performance", "Vendor Coupons", "Vendor Shipping", "Vendor Tax Settings",
      "Vendor Dashboard", "Vendor Reports", "Marketplace Insights", "Global Marketplace Support",
    ],
  },
  {
    id: "franchise-dealer",
    number: 44,
    name: "Franchise & Dealer Management",
    shortName: "Franchise",
    category: "Sales & CRM",
    icon: "Store",
    description: "Franchise registration, dealer orders, territory & commissions",
    variant: "generic",
    features: [
      "Franchise Registration", "Dealer Management", "Distributor Management", "Territory Management",
      "Sales Territory", "Commission Management", "Franchise Dashboard", "Dealer Orders",
      "Dealer Inventory", "Dealer Payments", "Dealer Reports", "Franchise Analytics",
      "Dealer Support", "Branch Network", "Franchise Agreements", "Dealer Targets",
      "Dealer Performance", "Dealer Promotions", "Dealer Notifications", "Dealer Portal",
    ],
  },
  {
    id: "loyalty-rewards",
    number: 45,
    name: "Loyalty & Rewards",
    shortName: "Loyalty",
    category: "Sales & CRM",
    icon: "Gift",
    description: "Loyalty points, membership, cashback, coupons, referrals",
    variant: "generic",
    features: [
      "Loyalty Points", "Membership Levels", "Reward Points", "Cashback",
      "Coupons", "Gift Cards", "Referral Rewards", "Birthday Rewards",
      "Anniversary Rewards", "Promotional Campaigns", "Customer Wallet", "Loyalty Reports",
      "Customer Rewards", "VIP Membership", "Special Discounts", "Redeem Points",
      "Reward Notifications", "Customer Engagement", "Loyalty Analytics", "Marketing Dashboard",
    ],
  },
  {
    id: "affiliate",
    number: 46,
    name: "Affiliate Management",
    shortName: "Affiliate",
    category: "Sales & CRM",
    icon: "Share2",
    description: "Affiliate registration, referral links, commissions, payouts",
    variant: "generic",
    features: [
      "Affiliate Registration", "Affiliate Dashboard", "Referral Links", "Commission Tracking",
      "Affiliate Wallet", "Payout Requests", "Coupon Codes", "Campaign Tracking",
      "Click Analytics", "Conversion Tracking", "Affiliate Reports", "Payment History",
      "Referral Bonuses", "Marketing Materials", "Banner Management", "Multi-Level Referral",
      "Affiliate Notifications", "Fraud Detection", "Affiliate Performance", "Global Affiliate Support",
    ],
  },
  {
    id: "visitor-gate-pass",
    number: 47,
    name: "Visitor & Gate Pass",
    shortName: "Visitor",
    category: "Operations",
    icon: "DoorOpen",
    description: "Visitor registration, QR gate pass, security approval",
    variant: "generic",
    features: [
      "Visitor Registration", "Visitor Pass", "QR Gate Pass", "Visitor Photo",
      "Visitor ID Verification", "Appointment Booking", "Security Approval", "Gate Entry",
      "Gate Exit", "Visitor History", "Visitor Reports", "Visitor Notifications",
      "Host Notifications", "Vehicle Entry", "Vehicle Pass", "Visitor Dashboard",
      "Visitor Analytics", "Security Logs", "Digital Register", "Visitor Management Reports",
    ],
  },
  {
    id: "legal-contract",
    number: 48,
    name: "Legal & Contract Management",
    shortName: "Legal",
    category: "System",
    icon: "FileSignature",
    description: "Contracts, NDAs, e-signature, renewals, expiry alerts",
    variant: "generic",
    features: [
      "Contract Management", "Digital Agreements", "E-Signature", "Legal Documents",
      "NDA Management", "Vendor Contracts", "Employee Contracts", "Customer Agreements",
      "Contract Renewal", "Expiry Alerts", "Legal Approval", "Legal Reports",
      "Compliance Tracking", "Policy Management", "Document Security", "Version Control",
      "Legal Dashboard", "Contract Analytics", "Digital Archive", "Legal Notifications",
    ],
  },
  {
    id: "esg-sustainability",
    number: 49,
    name: "ESG & Sustainability",
    shortName: "ESG",
    category: "Advanced",
    icon: "Leaf",
    description: "Carbon footprint, energy, water, waste, ESG reports",
    variant: "generic",
    features: [
      "Carbon Footprint Tracking", "Energy Monitoring", "Water Consumption", "Waste Management",
      "Sustainability Reports", "Environmental Compliance", "Social Compliance", "Governance Reports",
      "ESG Dashboard", "Carbon Reports", "Compliance Score", "Supplier Sustainability",
      "Green KPI", "Sustainability Goals", "ESG Analytics", "Audit Reports",
      "Environmental Alerts", "CSR Reports", "Global Compliance", "ESG Documentation",
    ],
  },
  {
    id: "communication-hub",
    number: 50,
    name: "Enterprise Communication Hub",
    shortName: "Comms Hub",
    category: "Advanced",
    icon: "MessagesSquare",
    description: "Internal chat, voice/video meetings, announcements, forums",
    variant: "generic",
    features: [
      "Internal Chat", "Team Messaging", "Voice Calls", "Video Meetings",
      "Group Chat", "Announcement Board", "Company News", "File Sharing",
      "Calendar", "Task Assignment", "Meeting Scheduler", "Email Integration",
      "WhatsApp Integration", "Push Notifications", "Employee Directory", "Discussion Forum",
      "Polls & Surveys", "Communication Reports", "Communication Analytics", "Team Channels",
    ],
  },
];

export const getModuleById = (id: string) => MODULES.find((m) => m.id === id);
