"use client";

import { ShoppingCart, Truck, Warehouse, Landmark, Users, ReceiptText, FileText, Download, Filter, FileSpreadsheet, FileDown } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { PageHeader } from "../ui/PageHeader";
import { DataTable, StatusBadge, type Column } from "../ui/DataTable";
import { reportCategories, recentReports } from "@/lib/erp/demo-data";

const iconMap: Record<string, any> = {
  ShoppingCart, Truck, Warehouse, Landmark, Users, ReceiptText,
};

interface Report {
  id: string; name: string; category: string; generatedAt: string; size: string; format: string; by: string;
}

const columns: Column<Report>[] = [
  { key: "id", header: "ID", render: (r) => <span className="font-mono text-xs font-semibold text-indigo-400">{r.id}</span> },
  {
    key: "name",
    header: "Report Name",
    render: (r) => (
      <div className="flex items-center gap-2">
        <FileText className="h-4 w-4 text-muted-foreground" />
        <span className="text-sm font-medium text-foreground">{r.name}</span>
      </div>
    ),
  },
  {
    key: "category",
    header: "Category",
    render: (r) => <span className="rounded-md bg-card px-2 py-0.5 text-xs text-foreground">{r.category}</span>,
  },
  {
    key: "format",
    header: "Format",
    align: "center",
    render: (r) => (
      <StatusBadge variant={r.format === "PDF" ? "danger" : "success"}>{r.format}</StatusBadge>
    ),
  },
  { key: "size", header: "Size", align: "right", render: (r) => <span className="text-xs text-muted-foreground">{r.size}</span> },
  { key: "by", header: "Generated By", render: (r) => <span className="text-xs text-foreground">{r.by}</span> },
  { key: "generatedAt", header: "Generated", align: "right", render: (r) => <span className="text-xs text-muted-foreground">{r.generatedAt}</span> },
  {
    key: "actions",
    header: "",
    align: "right",
    render: () => (
      <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground">
        <Download className="h-4 w-4" />
      </Button>
    ),
  },
];

export function ReportsModule() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports & Analytics"
        subtitle="Sales, purchase, inventory, finance, HR & custom reports"
        icon={FileText}
        iconColor="#14b8a6"
        showSearch
        actions={
          <>
            <Button variant="outline" size="sm" className="h-9 border-border bg-card text-foreground hover:bg-card/80">
              <Filter className="mr-1.5 h-4 w-4" /> Filters
            </Button>
            <Button variant="outline" size="sm" className="h-9 border-border bg-card text-foreground hover:bg-card/80">
              <FileSpreadsheet className="mr-1.5 h-4 w-4" /> Export Excel
            </Button>
            <Button variant="outline" size="sm" className="h-9 border-border bg-card text-foreground hover:bg-card/80">
              <FileDown className="mr-1.5 h-4 w-4" /> Export PDF
            </Button>
          </>
        }
      />

      {/* Report category cards */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-3 xl:grid-cols-6">
        {reportCategories.map((c) => {
          const Icon = iconMap[c.id] ?? FileText;
          return (
            <Card
              key={c.id}
              className="card-hover group cursor-pointer border-border bg-card p-4"
            >
              <div
                className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg transition-transform group-hover:scale-110"
                style={{ backgroundColor: `${c.color}1a`, color: c.color }}
              >
                <Icon className="h-5 w-5" />
              </div>
              <p className="text-sm font-semibold text-foreground">{c.name}</p>
              <p className="mt-0.5 text-xs text-muted-foreground">{c.count} reports available</p>
            </Card>
          );
        })}
      </div>

      {/* Quick stats */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {[
          { label: "Reports Generated", value: "248", color: "#3b82f6" },
          { label: "Scheduled Reports", value: "36", color: "#8b5cf6" },
          { label: "Custom Templates", value: "18", color: "#10b981" },
          { label: "Pending Generation", value: "4", color: "#f59e0b" },
        ].map((s) => (
          <Card key={s.label} className="border-border bg-card p-4">
            <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{s.label}</p>
            <p className="mt-2 text-2xl font-bold" style={{ color: s.color }}>{s.value}</p>
          </Card>
        ))}
      </div>

      <Card className="border-border bg-card p-5">
        <div className="mb-4 flex items-center justify-between">
          <div>
            <h3 className="text-sm font-semibold text-foreground">Recently Generated Reports</h3>
            <p className="text-xs text-muted-foreground">{recentReports.length} recent reports</p>
          </div>
        </div>
        <DataTable columns={columns} data={recentReports} />
      </Card>
    </div>
  );
}
